## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [5]:
def divide(a, b):
    try:
        return a/b
    except ZeroDivisionError:
        print('ZeroDivisionError')
print(divide(5,0))

ZeroDivisionError
None


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [7]:
for x in ['Americans','Indians']:
    for y in ['play','watch']:
        for z in ['Baseball','Cricket']:
            print(x + " " + y + " "+ z)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [8]:
import numpy as np
def vander(lst, increasing = True):
    arr = np.array(lst)
    output_mat = np.vander(arr, increasing = increasing)
    return output_mat
print(vander([1,2,3,4]))
print(vander([1,2,3,4], False))

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
